import PublicPageShell from "@/components/PublicPageShell";

export const metadata = { title: "Terms of Service | NaijaMarket Intel" };

export default function TermsPage() {
  return (
    <PublicPageShell
      title="Terms of Service"
      subtitle="The rules that govern your use of NaijaMarket Intel."
    >
      <p className="pp-date">Last updated: February 23, 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using NaijaMarket Intel (&quot;the Platform&quot;), operated by
        Giggababytes Oy (&quot;the Company&quot;), you agree to be bound by these Terms of
        Service. If you do not agree, do not use the Platform.
      </p>

      <h2>2. Service Description</h2>
      <p>
        NaijaMarket Intel is a commodity price intelligence platform that provides
        crowdsourced, GPS-verified market prices across Nigeria. The Platform
        operates through web and WhatsApp interfaces and offers tiered subscription
        plans from FREE to ENTERPRISE.
      </p>

      <h2>3. User Accounts</h2>
      <ul>
        <li>You must provide accurate and complete registration information</li>
        <li>You are responsible for maintaining the confidentiality of your account</li>
        <li>One account per person — account sharing is prohibited</li>
        <li>You must be at least 18 years old to use the Platform</li>
        <li>We reserve the right to suspend or terminate accounts that violate these terms</li>
      </ul>

      <h2>4. Trader Terms</h2>
      <div className="pp-card">
        <p>If you submit price data as a Trader, you agree to:</p>
        <ul>
          <li>Submit accurate, truthful commodity prices from physical markets</li>
          <li>Be physically present at the market when submitting prices (GPS verification required)</li>
          <li>Not use GPS spoofing, mock locations, or any location manipulation tools</li>
          <li>Not collude with other traders or validators to manipulate prices</li>
          <li>Accept that fraudulent submissions will result in reputation penalties and potential account termination</li>
        </ul>
        <p>
          <strong>Rewards:</strong> Approved submissions earn ₦20 in airtime credits.
          Minimum payout balance is ₦500. Payouts are processed weekly on Fridays.
        </p>
      </div>

      <h2>5. Validator Terms</h2>
      <div className="pp-card">
        <p>If you participate as a Validator, you agree to:</p>
        <ul>
          <li>Provide honest, independent assessments of price submissions</li>
          <li>Not coordinate votes with other validators or traders</li>
          <li>Complete validations within the 30-minute deadline</li>
          <li>Accept that inaccurate validations affect your accuracy score</li>
        </ul>
        <p>
          <strong>Rewards:</strong> Majority-consensus validations earn ₦50 in airtime
          credits. Validators below 60% accuracy may be suspended.
        </p>
      </div>

      <h2>6. Subscription Terms</h2>
      <ul>
        <li>FREE tier users receive limited queries per day at no cost</li>
        <li>Paid subscriptions (SILVER, GOLD, BUSINESS, CORPORATE, ENTERPRISE) are billed monthly</li>
        <li>Subscriptions auto-renew unless cancelled before the renewal date</li>
        <li>Refunds are not provided for partial months — you retain access until the period ends</li>
        <li>Enterprise subscriptions require a separate service agreement</li>
      </ul>

      <h2>7. Prohibited Conduct</h2>
      <ul>
        <li>Submitting false or misleading price data</li>
        <li>Using GPS spoofing or location manipulation tools</li>
        <li>Creating multiple accounts to earn additional rewards</li>
        <li>Scraping, crawling, or automated access to the Platform without API authorization</li>
        <li>Attempting to reverse-engineer or compromise Platform security</li>
        <li>Using the Platform for any unlawful purpose</li>
      </ul>

      <h2>8. Intellectual Property</h2>
      <p>
        All content, data, analytics, algorithms, and technology on the Platform are
        owned by Giggababytes Oy. Aggregate market data and analytics generated by
        the Platform may not be reproduced, distributed, or commercially exploited
        without a valid API or Enterprise subscription.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        NaijaMarket Intel provides market intelligence for informational purposes
        only. We do not guarantee the accuracy, completeness, or timeliness of any
        price data. The Platform is not a substitute for professional financial,
        procurement, or investment advice. We are not liable for any losses incurred
        from decisions made based on Platform data.
      </p>

      <h2>10. Governing Law</h2>
      <p>
        These Terms are governed by the laws of <strong>Finland</strong> and the
        <strong> Federal Republic of Nigeria</strong>. Disputes shall be resolved
        through arbitration in accordance with the Arbitration and Conciliation Act
        of Nigeria, unless otherwise required by applicable law.
      </p>

      <h2>11. Contact</h2>
      <p>
        For questions about these terms, contact us at{" "}
        <a href="mailto:legal@naijamarketintel.ng">legal@naijamarketintel.ng</a>.
      </p>
    </PublicPageShell>
  );
}
